apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rag-database
  namespace: rag-experiment
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  encryptedData:
    groq-api-key: AgCXEl0fKH/5mP1qSaLLudLBRMI1qjtDKmWbhGkr6QPCPNvpDRoJvmgRB4igbVy9oRABVG+4HDiKCkObAYBAwglBlagPY601R98PdDZXzQiHIuaQM27Rxts3YbPoj12Q3lGFXewvz4kUQrTYLF4+SKd8j9CnwOrjVLAuyO46qmoVUkIqkq6kVtChfS2hXWroWhiA7ppWr7QdeIBuNX7U5CF8EYD9KFP0tg+PVrHO8DTlKuMkw3S54i7IJkr+k5U7qzfyFjdhOwxmeRzvrtyH/QiSEUpVOxL9Oi3orqbcQf6H42nZtKTbvfzGSdzXKTzPM5ZECuarBcKyHEace9+1jv86hIX3X2ifOBD5SrDd5s4atIeSr5nUuFXqo0SvoAOCdjECmnFoizP0pyUpXl1s9feYrHK48ebWPAfPccuptIwO3J+STdWr5uDEtemawCvH88t5vk3TUyYxnUChtUj6A0z5TrTeuB+vfa7fvKGKoli+nrEw/qM8aFXIR/I9ErjYjP74YMpH47T3ygkEO6h5CGulqqcE0H2cPVeyWgqYZwX1QGnWBchDZyuag64ah5Nw00cxGAwBrt07ghx1C1YGZ2ImAcTkXRusDLC63B1M5BElkEfMOFw+BzMIpGWa04b3FBQv2/32Agk4hAEzQtVNZNMjwKFrYB0W1qxUbWx1oK+t3IelnhwU7j9De+tYnv1Jr4v7jBQY/LCLWsWkH485d+Ute6noTMez6mL2FsjMD96346x4dSz3Z5rjjEBNyZDRzX+czMasbNtz8w==
  template:
    metadata:
      name: rag-database
      namespace: rag-experiment