apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
  name: rag-database
  namespace: rag-experiment
spec:
  encryptedData:
    groq-api-key: AgC7qxHMi2yKQFb2QnANveHNzjtMFiA4e+2+XOLyLAy514o0mNU9eg1STRPMgMRTSy/wCl5urnu3OZxVZWlg65tVNrDfIuFmjw0Jxeq4KSWlQapgOiFI/Au5w5I4Gf5krM4sg65bNHCFu48MLlYkEA7eYZYnam09woC0eOxZ/Q8P7ZDaGtJVpuFWSBlo0s2r5JDZhhcsNh6UlHP0sjG9Gqij9DnFo3OHtDCn/gYFe+YIIfO1rwKd4EnjF5GPHpyG6yXzyVhrQTgojmgHezRQUAgttBEQmOJUzO5hqBvzQatRHmed/cm9NUHDUwv6NeU7/CAhBuVSiPaV6kh0BjMWqVDNN3SQwjSBjjMAZZy37aec/uwEtsZ4zEdCMvFi4u2zlZ8cyXtCuoIHvJePdIShkEBuu6fcvum/fmbGKLd6+ZfmBbEQvDS62kzIuyJwD4m2U9EWb1bvb+5QkIH/bapYN0HyKU+9JrVNIF0KkPAGDhqrV3MNb6DIjkMMlZl9g06G6mcrd+80Q05ch5SznBjTGj9uDrFGwjaYwFXPiqMbLAFTjl4qV3URmCBqkl79VgLcz/HDmtYUEAMccZsTXZq+8aTe5dqaQuoymQlxuz0/pPLVmdn5AczqiZ3t+lwSaP2gWZgXYtirn4c4nDTVECmQIhkpP+q+LM3zCZQIArjMtVApJqlFuM8kjmsQrPAJGsRDFY0=
  template:
    metadata:
      name: rag-database
      namespace: rag-experiment