apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rag-database
  namespace: rag-experiment
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  encryptedData:
    groq-api-key: AgC5UmCju7Kz7pFivwdDYIsv2kajgZ82ksr+u5ZS6JSNU4dgmKBbjxCO70MBjQS4HQi/KhnkI1iZw72daqYcoxrZxQ8ImZw8MdcPT1LX9O88c0LkdTkFLqEibBQr40aMfqlC2gt71F0QwoiZ8FOLiyz3mRCG7WgrgI8AfiIFsbHboYSy9DAWQOrWJpvz3k6A7ivOOJDkYWuBYBErbd8vw09f7wg4j9FwuZ5wRTwu9NDYFgvtUGRSey/DPFLQhCkhdK4hFgsPaL7nUXQJCz2/oSrst5kwfFDqJQXF/RpmL5bttvYzM1tj6Mn28D+pd4kl+tkscFnc/p95qC7jgMZzSZwA39blnBAKyq8iqoJbsOl+f/4FEYRl5f9em/NYLfPlu4Ua7GF3uDNAQNfdUG4ZW83SEtm3k70zqe/AWrrP/yjFgjLJtiaB1Panj1PzaOej33uSunFHNnsiPnPNQ8VgBKNyLrimpcDVt/Ty2bEWPQWzoUDl+7icwT4JwCHHMgamb+jnwVA+wdE09MBjj5nik0RZnKABTLLzgljiHasssFp/+fCFQPbCQtKgC2ZH+3JvAxJuDUXMowu7EfhZwpJZHHKXVRaGkK+FszYRADVqrmqkSId11oHA6GHc/aq0k4+n3tAOyJuNSU2JVqrZWEEGQ5V7S0I00EKbaYYPYfM1j+PwNAcfsO+ptVXDaCyjkm5M4Ft4bd3C8WxvU/3WdLOBvigRfIdVbmgdyXXICGH8+8fB2cDR9YJWM5Y9OaMB2U25CHUlbLq2PDEURw==
  template:
    metadata:
      name: rag-database
      namespace: rag-experiment