apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3s-prod-credentials
  namespace: infisical-operator
spec:
  encryptedData:
    # Encrypted with kubeseal using the cluster sealed-secrets public key
    clientId: ""
    clientSecret: ""
  template:
    metadata:
      name: k3s-prod-credentials
      namespace: infisical-operator
