apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: francais-tout-en-un
resources:
  - namespace.yaml
  - database.yaml
  - redis.yaml
  - auth-service.yaml
  - course-service.yaml
  - entitlement-service.yaml
  - react-nginx.yaml
