apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: ceo-resolver-secrets
  namespace: ceo
spec:
  infisicalAuthRef:
    name: k3s-prod-auth
    namespace: infisical-operator

  syncOptions:
    refreshInterval: 1m

  sources:
    - projectSlug: ceo-state-mcp-qcm-7
      environmentSlug: prod
      secretPath: /content-resolver

  targets:
    - name: ceo-resolver-secrets
      namespace: ceo
      kind: Secret
      creationPolicy: Owner
