apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceo
resources:
  - namespace.yaml
  - git-known-hosts.yaml
  - infisical-secret.yaml
  - server-deployment.yaml
  - server-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - resolver-infisical-secret.yaml
  - resolver-deployment.yaml
  - resolver-service.yaml
  - ingress.yaml
  - redis-infisical-secret.yaml
  - redis-configmap.yaml
  - redis-pvc.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
