apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceo-redis-data
  namespace: ceo
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
