---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lifeos-git
  namespace: lifeos-mcp
spec:
  encryptedData:
    ssh-privatekey: AgADivAehWha8hgLqWa5A8p+By4lKe4k2FRT11LB8iF8S7GqokXRTK80dONZO/6ARMCUCnAKDt88Fojl8UgBh3jM1gHxDYLgVURWUz/b3h9ui5rYuFNv1gA1kJIfBuFBCGKcgagXhNUHgbigQHARv/L+l6yCcJaUDbe9dAan8S73eaya99c2VvBTsob8oCbdthR4zpJ8Je59rruMCcdBk42vRqA4RkN5SERllw6+LWW3NwEU9MbxHo6uzVlYSyGpSBJrfWArxRLq5gSYab32oQma9cRfNo34ZL/VuqvBaVSqZ1SoQDnsOs5KgUC51iOaBTEP2BcnTeDl/5YDNer7mLPxb9mGzyxTYH9ycCY8XYG1Ba4iGEquwVaZhEignlHrbeXgziArH3qHXXmEuQL+56AkPuMJSyC+2a5o/KLpW6ZSl1By4EuF0TLDxUFf3IJoJwjrsoW07aAnhQ+MVH6VvBhTEYE36NGU3hUEVjYoeZEg+EkSpx+4Jd8GtBcf2wFTu+VcqXo+T6ZYZDW8DJzICrR5fnGp0uOPLxPpm7znQUoXFybu/AuAFYzUKO5fiE93VFMJfx4WTRW47sJCbvp+JMUVrdZrEOGr+1jp0ksYDAl6P767yc2YIM4Y0st6ucBBLlybK2KPJLlKrER51Y1eemuVNciu6spRq/giewEyHTUgxJFP46+oFOD+c7LBRQ0HoeFj3j+sVNAVT+geye2DKuPQT9N2ujgj4tkoTcHMeZGGMOy42RXSKJ4deAxEhwYmn1QBM8RcNXUlQ34sgxc66/2wbWTw5c6oxqkVF8Nre3pw9ZaWszOrxV9hWAJIKfgwDu3AKT6wDlK0u89aJM+XVOFU1aDI1isywnpQ4jzp+zD6DM7hqbIRUdl/NXZzEwoF3s4YeX5ofIaJ2N+4/JtrVNejpU4HkLgq2dQannutRPEj5Ydtlp4FyIbV/Isl0h1U5wproYX3ocxGvNIfphjH0vnZ6sgMfaJ2jKRMPyxPI+4qrTMYO0i26EVkuDQ5Zw0QI9SsHq9UQIdMK0c/SKRH6vY1/XEJ5MY8SBct2kUPktNRJx1Y8oJWe4JWumdwflh8UHtoinjP2DKmG/pxP5og+aPZVEBw8N6t+pDg27ZOJkrifo6PwkgT2H+GakG4jE+nwRt0rKa2FGHuUO+JiHXz64rD2scmXMFJg3mhWuFWDMitTtlZGj1IAf1Z2u109IIObqalFGT+luvOfhxpjudT1BuJZKT68mr+k3DiVP8=
  template:
    metadata:
      name: lifeos-git
      namespace: lifeos-mcp
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lifeos-mcp-auth
  namespace: lifeos-mcp
spec:
  encryptedData:
    api-key: AgBgP4Gh8LiYrFlutrjDrlRD2TuGiNm54SAe7Csmwl7ATLQGhFc2kQd4kOwD1VmvUBWMzZyZEqSDanp9B9nWyW5L6RDl2by/H/PGywEL9xS+siD2EHRKwoYSQPdHOgVsHO40FnppaO/rG0pJYsxsxsy+8d41cqCJ6f9XrW5McKjW8j4cw2rDOoHSO7zufDWt+UDNJk6z9HKYsr7Q/1M7rS+bVyjAbJ52ntXmY1Zgc5amvfP7IAWw6dVai7s8xQ0LBi4kVjZr/K3DgVkCRZfz8puxPQaWtGpbhEOa9wh1FnERAZUbOcbciFfv2DihytSPvxuYZnqBHSxqt/d9hMIsq3KngsigOnDKEJPSNjA0HnOYtVduYuNnc9tFZh0RUHQyR81GIJ9hjNN6CCyb/C8MlOFDPPwwgcSmpnEJIgkb5qYYBDEnFMLzUqwb2XGteqvExdut9oGKB0rZhCV1CWYtI48RVry72kAjvRLbFNVP9Zttuw35s2rlH1eMIcOjs4TWulDA5o4hN/ZAp35jDtbN4mWRBXCfBh2EZi0zZwoyyYOB1iYWnAB/lINs0vk9ldVdi98gjJnpquYaApe7ReeslfdXkgf6VETxTDlf1sDeqlR2NV0hmS+VPa07K/AqElSZrOljXjvRUYRGst1vN4vxYf9Imh+KzLhbnZFiznyE8ACbWC82Kx93wgm9a9p/35TwjwQTV6xDQdjZCjyhZqfEHsyILti/0zUK/pcA66JojlP2avpR+4TZ8J5PTOraE52qrkrLUNM8lKxN1WjtDF4iidcc
  template:
    metadata:
      name: lifeos-mcp-auth
      namespace: lifeos-mcp