apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reliquary
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - secret.yaml
  - sensevoice-deployment.yaml
  - sensevoice-service.yaml
