apiVersion: v1
kind: Service
metadata:
  name: reliquary-sensevoice
  namespace: default
  labels:
    app: reliquary-sensevoice
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: reliquary-sensevoice
  type: ClusterIP
