apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: content-resolver-secrets
  namespace: content-resolver
spec:
  infisicalAuthRef:
    name: k3s-prod-auth
    namespace: infisical-operator

  syncOptions:
    refreshInterval: 1m

  sources:
    - projectSlug: shared-infra-vm-gs
      environmentSlug: prod
      secretPath: /content-resolver

  targets:
    - name: content-resolver-secrets
      namespace: content-resolver
      kind: Secret
      creationPolicy: Owner
