apiVersion: v1
kind: Service
metadata:
  name: content-resolver
  namespace: content-resolver
  labels:
    app: content-resolver
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: content-resolver
