apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-snoopy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SentimentalK/k3s-homelab.git
    targetRevision: master
    path: apps/snoopy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
