apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: tracking-tool-secrets
  namespace: tracking-tool
spec:
  infisicalAuthRef:
    name: k3s-prod-auth
    namespace: infisical-operator

  syncOptions:
    refreshInterval: 1m

  sources:
    - projectSlug: tracking-tool
      environmentSlug: prod
      secretPath: /

  targets:
    - name: tracking-tool-secrets
      namespace: tracking-tool
      kind: Secret
      creationPolicy: Owner
